apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeinisght
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codeinisght
  template:
    metadata:
      labels:
        app: codeinisght
    spec:
      containers:
        - name: app
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: Always
